#!/usr/bin/env zsh

CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Completions style
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}


### Load external tools first

if command -v mise 1>/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

export SHELDON_CONFIG_DIR="${CONFIG_HOME}/sheldon/zsh"
export SHELDON_DATA_DIR="${DATA_HOME}/sheldon/zsh"
 
if command -v sheldon  1>/dev/null 2>&1; then
  eval "$(sheldon source)"
fi


# Aliases

[[ -f ${CONFIG_HOME}/aliases ]] && source ${CONFIG_HOME}/aliases

# Add personal functions and completions to fpath

if [[ ( -d ${CONFIG_HOME}/zsh/.zshrc.d ) && ( -n "$(ls -A ${CONFIG_HOME}/zsh/.zshrc.d)" ) ]]; then
	for rc in ${CONFIG_HOME}/zsh/.zshrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

fpath=( ${CONFIG_HOME}/zsh/functions "${fpath[@]}" )
fpath=( ${CONFIG_HOME}/zsh/completions "${fpath[@]}" )
autoload -Uz $fpath[1,2]/*(.:t)

autoload -Uz compinit

if [[ -n $ZDOTDIR/.zcompdump(#qN.mh+24) ]]; then
  compinit
  touch $ZDOTDIR/.zcompdump
else
  compinit -C
fi

### p10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ${CONFIG_HOME}/zsh/.p10k.zsh ]] || source ${CONFIG_HOME}/zsh/.p10k.zsh

### End of p10k

# if command -v starship  1>/dev/null 2>&1; then
#   eval "$(starship init zsh)"
# elif command -v $(mise which starship) 1>/dev/null 2>&1;then
#   eval "$(mise exec starship -- starship init zsh)"
# fi

# vim: ft=bash
