#!/usr/bin/env zsh
 
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Load external tools first

if command -v mise 1>/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

if command -v sheldon  1>/dev/null 2>&1; then
  eval "$(sheldon source)"
fi

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Aliases

[[ -f ~/.config/aliases ]] && source ~/.config/aliases

# Add personal functions and completions to fpath

if [[ ( -d ~/.config/zsh/.zshrc.d ) && ( -n "$(ls -A ~/.config/zsh/.zshrc.d)" ) ]]; then
	for rc in ~/.config/zsh/.zshrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

fpath=( ~/.config/zsh/functions "${fpath[@]}" )
fpath=( ~/.config/zsh/completions "${fpath[@]}" )
autoload -Uz $fpath[1,2]/*(.:t)

autoload -Uz compinit

if [[ -n $ZDOTDIR/.zcompdump(#qN.mh+24) ]]; then
  compinit
  touch $ZDOTDIR/.zcompdump
else
  compinit -C
fi

### p10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

### End of p10k

# if command -v starship  1>/dev/null 2>&1; then
#   eval "$(starship init zsh)"
# elif command -v $(mise which starship) 1>/dev/null 2>&1;then
#   eval "$(mise exec starship -- starship init zsh)"
# fi

# vim: ft=bash
