# ~/.config/starship.toml

# A minimal left prompt
format = """
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character\
"""

# move the rest of the prompt to the right
right_format = """
$all\
$username\
$hostname"""

[sudo]
format = '[$symbol]($style)'
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
version_format = '${raw}'
style = 'cyan'

[username]
format = ' [$user]($style)'
style_user = '243'
style_root = 'red'

[hostname]
format = '[@$hostname]($style)'
style = '243'

[git_branch]
style = 'green'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'
typechanged = ""
style = 'yellow'
ignore_submodules = false
disabled = false

[package]
disabled = true

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
detect_extensions = ['yaml', 'yml']
disabled = false

[vagrant]
format = '[$symbol($version )]($style)'
version_format = '${raw}'
style = 'blue'
