# ~/.config/starship.toml

# A minimal left prompt
format = """
$shell\
$directory\
$character\
"""

# move the rest of the prompt to the right
right_format = """
$all\
$username\
$hostname"""

[python]
symbol = ""

[username]
format = ' [$user]($style)'

[hostname]
format = '[@$hostname]($style)'

[shell]
disabled = true
